/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hi.dagskra.vidmot;
import is.hi.dagskra.gogn.Root;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * dialog gluggi þar sem dagskrárliður er skoðaður
 * @author Valdimar Ágúst  vae11@hi.is
 */
public class SkodaDagskrarLid extends javax.swing.JDialog {

    /**
     * Creates new form SkodaDagskrarLid
     * @param parent glugginn sem kallar á samtalsgluggann
     * @param modal ef satt þá verður samtalsglugganum að vera lokað áður en haldið er áfram og annað er gert
     */
    public SkodaDagskrarLid(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();


    }
    /**
     * setur gögn um dagskrárliði í viðmótshluti (titil, lysingu, etc. í jTitill, jLysing etc)
     *     
     * @param dagskrarlidur dagskrárliðurinn
     */
    public void setjaGogn(Root.Results dagskrarlidur){
        

        String titill = "" + dagskrarlidur.getTitle();
        String upphafstimi = "Upphafstimi: " + dagskrarlidur.getStartTime().substring(11,16);
        String seria = String.valueOf(dagskrarlidur.getSeries().getSeries()) ;
        String þattur = String.valueOf(dagskrarlidur.getSeries().getEpisode());
        String seriaOgÞattur = ("Sería " + seria) + (" Þáttur " + þattur);
        String lysing = "Lýsing: " + dagskrarlidur.getDescription();    
        
        XMLGregorianCalendar timalengd = dagskrarlidur.getDuration();
        String timalengdKlstMin = "Tímalengd: " + timalengd.getHour() + (" klst og " + (timalengd.getMinute() + " mín"));
        
        if(dagskrarlidur.getLive().equals("true")){
            jLive.setText("Í beinni útsendingu");       
        }else{
            jLive.setText("Ekki í beinni útsendingu"); 
        }
        jTitill.setText(titill);
        jUpphafstimi.setText(upphafstimi);
        jLysing.setText(lysing);
        jS7E8.setText(seriaOgÞattur);
        jTimalengd.setText(timalengdKlstMin);
       

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitill = new javax.swing.JLabel();
        jUpphafstimi = new javax.swing.JLabel();
        jTimalengd = new javax.swing.JLabel();
        jS7E8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLysing = new javax.swing.JTextArea();
        jLive = new javax.swing.JLabel();
        jLoka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTitill.setText("jLabel1");

        jUpphafstimi.setText("jLabel2");

        jTimalengd.setText("jLabel2");

        jS7E8.setText("jLabel2");

        jLysing.setEditable(false);
        jLysing.setColumns(20);
        jLysing.setLineWrap(true);
        jLysing.setRows(5);
        jLysing.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jLysing);

        jLoka.setText("Loka");
        jLoka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLokaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTitill, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jUpphafstimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTimalengd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jS7E8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLoka)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTitill, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jUpphafstimi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTimalengd)
                        .addGap(23, 23, 23)
                        .addComponent(jS7E8)
                        .addGap(18, 18, 18)
                        .addComponent(jLive, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLoka)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLokaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLokaActionPerformed
        dispose();
    }//GEN-LAST:event_jLokaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkodaDagskrarLid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkodaDagskrarLid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkodaDagskrarLid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkodaDagskrarLid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SkodaDagskrarLid dialog = new SkodaDagskrarLid(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLive;
    private javax.swing.JButton jLoka;
    private javax.swing.JTextArea jLysing;
    private javax.swing.JLabel jS7E8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTimalengd;
    private javax.swing.JLabel jTitill;
    private javax.swing.JLabel jUpphafstimi;
    // End of variables declaration//GEN-END:variables
}
