/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hi.dagskra.vidmot;
import is.hi.dagskra.gogn.Root;
/**
 *  Gluggi þar sem liður er skráður í Mína Dagskrá 
 * @author Valdi
 */
public class SkraLidMinDagskra extends javax.swing.JDialog {
    /**
     * titill nýja liðarins
     */
    private String titill;
    /**
     * upphafstími nýja liðarins á sniðinu [hh:mm]
     */
    private String upphafstimi;
    /**
     * true ef á morgun, false ef í dag
     */
    boolean aMorgun = false;
    
    /**
     * 
     */
    private final AdalDagskra dagskrarGlugginn;
     
    /**
     * Creates new form SkraLidMinDagskra
     */
    public SkraLidMinDagskra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);   
        dagskrarGlugginn = (AdalDagskra) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelNyr = new javax.swing.JLabel();
        jSkra = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitill = new javax.swing.JLabel();
        jTextTitill = new javax.swing.JTextField();
        jLabelUpphafstimi = new javax.swing.JLabel();
        jTextUpphafstimi = new javax.swing.JTextField();
        jButtonIDag = new javax.swing.JRadioButton();
        jButtonMrg = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNyr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelNyr.setText("Nýr dagskrárliður");

        jSkra.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jSkra.setText("Skrá");
        jSkra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSkraActionPerformed(evt);
            }
        });

        jLabelTitill.setText("Titill:");

        jTextTitill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTitillActionPerformed(evt);
            }
        });
        jTextTitill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextTitillKeyPressed(evt);
            }
        });

        jLabelUpphafstimi.setText("Upphafstími: [hh:mm]");

        jTextUpphafstimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUpphafstimiActionPerformed(evt);
            }
        });
        jTextUpphafstimi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextUpphafstimiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelUpphafstimi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelTitill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextTitill))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextUpphafstimi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitill)
                    .addComponent(jTextTitill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelUpphafstimi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUpphafstimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSkra)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNyr, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNyr, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSkra)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        buttonGroup1.add(jButtonIDag);
        jButtonIDag.setSelected(true);
        jButtonIDag.setText("í dag");
        jButtonIDag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIDagActionPerformed(evt);
            }
        });

        buttonGroup1.add(jButtonMrg);
        jButtonMrg.setText("á morgun");
        jButtonMrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIDag)
                    .addComponent(jButtonMrg))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButtonIDag)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMrg)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUpphafstimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUpphafstimiActionPerformed
        
        
    }//GEN-LAST:event_jTextUpphafstimiActionPerformed

    private void jTextTitillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTitillActionPerformed
                
        
    }//GEN-LAST:event_jTextTitillActionPerformed

    private void jSkraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSkraActionPerformed
        skraLid();
    }//GEN-LAST:event_jSkraActionPerformed

    private void jButtonIDagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIDagActionPerformed
        aMorgun = false;
    }//GEN-LAST:event_jButtonIDagActionPerformed

    private void jButtonMrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMrgActionPerformed
        aMorgun = true;
    }//GEN-LAST:event_jButtonMrgActionPerformed

    private void jTextTitillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTitillKeyPressed

    }//GEN-LAST:event_jTextTitillKeyPressed

    private void jTextUpphafstimiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUpphafstimiKeyPressed

    }//GEN-LAST:event_jTextUpphafstimiKeyPressed
    /**
     * Setur nýjan dagskrárlið með titil titill og upphafstíma upphafstimi í Mína Dagskrá
     */
    private void skraLid() throws RuntimeException{
        titill = jTextTitill.getText();
        if(jTextUpphafstimi.getText().matches("\\d\\d:\\d\\d" )){
            // strengurinn er á réttu sniði
            upphafstimi = jTextUpphafstimi.getText();
        }
        
        if(titill == null || titill.isEmpty() || upphafstimi == null || upphafstimi.isEmpty()){
            throw new RuntimeException("Á eftir að skrifa titil eða upphafstíma");
        }
       
        
        // set titil og upphafstíma í dagskramodelMinIDag/Mrg
        if(aMorgun){           
            String textiTilAdBirta = upphafstimi + " " + titill;
            dagskrarGlugginn.getDagskramodelMinMrg().addElement(textiTilAdBirta);                        
        }else{
            String textiTilAdBirta = upphafstimi + " " + titill;
            dagskrarGlugginn.getDagskramodelMinIDag().addElement(textiTilAdBirta);                                    
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkraLidMinDagskra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkraLidMinDagskra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkraLidMinDagskra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkraLidMinDagskra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SkraLidMinDagskra dialog = new SkraLidMinDagskra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jButtonIDag;
    private javax.swing.JRadioButton jButtonMrg;
    private javax.swing.JLabel jLabelNyr;
    private javax.swing.JLabel jLabelTitill;
    private javax.swing.JLabel jLabelUpphafstimi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jSkra;
    private javax.swing.JTextField jTextTitill;
    private javax.swing.JTextField jTextUpphafstimi;
    // End of variables declaration//GEN-END:variables
}
