/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hi.dagskra.vidmot;

/**
 * dialog gluggi til að staðfesta eyðingu á dagskrárlið
 * @author Valdimar Ágúst Eggertsson vae11@hi.is
 */
public class StadfestaEydinguGluggi extends javax.swing.JDialog {

    /**
     * glugginn sem kallað er á úr
    */
    AdalDagskra adalGlugginn; 
    
    /**
     * Creates new form StadfestaEydinguGluggi
     * @param parent - glugginn sem kallar á samtalsgluggann 
     * @param modal - ef satt þá verður notandi að ljúka samtalinu áður en 
     */
    public StadfestaEydinguGluggi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        adalGlugginn = (AdalDagskra) parent;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStadfesta = new javax.swing.JButton();
        jHaettaVid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jStadfesta.setText("Eyða!");
        jStadfesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStadfestaActionPerformed(evt);
            }
        });

        jHaettaVid.setText("Hætta við");
        jHaettaVid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHaettaVidActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ertu viss um að þú viljir eyða dagskrárliðnum?");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jStadfesta)
                        .addGap(55, 55, 55)
                        .addComponent(jHaettaVid)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStadfesta)
                    .addComponent(jHaettaVid))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * staðfestir eyðingu á dagskrárlið m.þ.a. gera stadfestaEyda í AdalDagskra true
     * @param evt 
     */
    private void jStadfestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStadfestaActionPerformed
        adalGlugginn.setStadfestaEyda(true);
        dispose();
    }//GEN-LAST:event_jStadfestaActionPerformed
    /**
     * lokar dialognum
     * @param evt 
     */
    private void jHaettaVidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHaettaVidActionPerformed
        dispose();
    }//GEN-LAST:event_jHaettaVidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StadfestaEydinguGluggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StadfestaEydinguGluggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StadfestaEydinguGluggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StadfestaEydinguGluggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StadfestaEydinguGluggi dialog = new StadfestaEydinguGluggi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jHaettaVid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jStadfesta;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
